version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./www:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  web:
    image: nginx:1.17-alpine
    depends_on:
      - php
    ports:
      - 10080:80
    volumes:
      - ./www/html:/var/www/html
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
