version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./www:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  web:
    image: nginx:1.17-alpine
    depends_on:
      - php
    ports:
      - 10080:80
    volumes:
      - ./www/html:/var/www/html
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      .env_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 4040:80
    depends_on:
      - db
    volumes:
      - ./phpmyadmin/session:/sessions
      - ./phpmyadmin/src:/var/www/html
